[package]
name = "substrace_declare_substrace_lint"
version = "0.2.0"
edition = "2021"
publish = true

[lib]
proc-macro = true

[dependencies]
itertools = "0.10.1"
quote = "1.0.21"
syn = "1.0.100"

[features]
deny-warnings = []
