[alias]
uitest = "test --test compile-test"
lintcheck = "run --package substrace_lintcheck --bin substrace_lintcheck --manifest-path substrace_lintcheck/Cargo.toml  -- "

[build]
# -Zbinary-dep-depinfo allows us to track which rlib files to use for compiling UI tests
rustflags = ["-Zunstable-options", "-Zbinary-dep-depinfo"]
target-dir = "target"

[unstable]
binary-dep-depinfo = true
