name: Build, test and Clippy

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2022-11-21
        components: clippy
    - name: Install ripgrep
      run: cargo install ripgrep --features 'pcre2'
    - name: Build
      run: cargo build --verbose
    - name: Lintcheck
      run: cargo lintcheck
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy --verbose