name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Format
        run: cargo fmt -- --check

      - name: Install cargo-dylint
        run: cargo install cargo-dylint

      - name: Install dylint-link
        run: cargo install dylint-link

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Doc Test
        # Doc-Tests cannot be run on "cdylib" crates.
        # Due to this the crate will be changed to a regular "lib" and then run the Doc-Tests.
        run: |
          sed -i 's/"cdylib"/"lib"/g' Cargo.toml
          cargo test --doc
